source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use PostgreSQL for the back end DB
gem 'pg'

# ------------------------------------
# Assets
# ------------------------------------
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# HAML for view templating
gem 'haml-rails'

# ------------------------------------
# Project
# ------------------------------------
# Session handling engine
gem 'devise'
# HTTP service parsing. May be needed in the future
gem 'httparty'

# ------------------------------------
# Deploy
# ------------------------------------
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Auto deployment on steroids
# gem 'mina'

group :development, :test do
  # ------------------------------------
  # Dev toolkit
  # ------------------------------------
  # Use pry console for debugging and $ rails console
  gem 'pry-rails'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  # Capture mailing in a HTML file
  gem 'letter_opener'
  # Suppress assets compilation
  gem 'quiet_assets'
  # Show me the money
  gem 'better_errors'

  # ------------------------------------
  # Test toolkit
  # ------------------------------------
  # Test coverage report
  gem 'simplecov', :require => false
  # Power factories instead of fixtures
  gem 'factory_girl_rails'
  # Driverless integration testing
  gem 'capybara'
end

